package com.wheel.safe.wheelsafe.bikeshop.entity;

public enum MaintenanceType {
    TIRE_REPAIR,
    BRAKE_ADJUSTMENT,
    GEAR_ADJUSTMENT,
    CHAIN_REPLACEMENT,
    WHEEL_TRUING,
    FRAME_ALIGNMENT,
    SUSPENSION_SERVICE,
    FORK_SERVICE,
    SHOCK_SERVICE,
    TUNE_UP,
    FULL_SERVICE,
    CUSTOM_SERVICE,
    ELECTRICAL_DIAGNOSTICS,
    BATTERY_REPLACEMENT,
    LIGHT_INSTALLATION,
    ACCESSORY_INSTALLATION,
    CUSTOM_INSTALLATION
}
